backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'mitarbeiter'
    label: 'Mitarbeiter'
    folder: 'content/mitarbeiter'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Beschreibung', name: 'mitarbeiterdescription', widget: 'string' }
      - { label: 'Email', name: 'mitarbeiteremail', widget: 'string', required: false }
      - { label: 'Bild', name: 'mitarbeiterimage', widget: 'image', allow_multiple: false }
  - name: 'woimages'
    label: 'Wo - Bilder'
    folder: 'content/wo'
    create: true
    slug: 'wo'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/wo'
    editor:
      preview: false
    fields:
      - label: 'Bilder'
        name: 'title'
        widget: 'list'
        fields:
          - { label: 'Alt-Text', name: 'alttext', widget: 'string' }
          - { label: 'Bild', name: 'mitarbeiterimage', widget: 'image', allow_multiple: false }
          - { label: 'Reihenfolge (zB. 0, 1, 2, a, b, ...)', name: 'order', widget: 'string', default: "z" }
