backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'mitarbeiter'
    label: 'Mitarbeiter'
    folder: 'content/mitarbeiter'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Beschreibung', name: 'mitarbeiterdescription', widget: 'string' }
      - { label: 'Email', name: 'mitarbeiteremail', widget: 'string' }
      - { label: 'Bild', name: 'mitarbeiterimage', widget: 'image', allow_multiple: false }