backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'mitarbeiter'
    label: 'Mitarbeiter'
    folder: 'content/mitarbeiter'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Beschreibung', name: 'mitarbeiterdescription', widget: 'string' }
      - { label: 'Email', name: 'mitarbeiteremail', widget: 'string', required: false }
      - { label: 'Bild', name: 'mitarbeiterimage', widget: 'image', allow_multiple: false }
  
  - label: "Wo - Bilder"
    name: "woimages"
    files:
      - label: "Bilder"
        name: "wobilder"
        file: "content/woimages.md"
        fields:
          - {label: Title, name: title, widget: hidden}
          - label: Bilder
            name: woimages
            widget: list
            fields:
              - { label: 'Alt-Text', name: 'alttext', widget: 'string' }
              - { label: 'Bild', name: 'mitarbeiterimage', widget: 'image', allow_multiple: false }
              - { label: 'Reihenfolge (zB. 0, 1, 2, a, b, ...)', name: 'order', widget: 'string', default: "z" }
