backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "mitarbeiter"
    label: "Mitarbeiter"
    folder: "content/mitarbeiter"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Beschreibung", name: "mitarbeiterdescription", widget: "string" }
      - { label: "Email", name: "mitarbeiteremail", widget: "string", required: false }
      - { label: "Bild", name: "mitarbeiterimage", widget: "image", allow_multiple: false }
      - { label: "Reihenfolge", name: "order", widget: "string", default: "9" }

  - name: "projekte"
    label: "Projekte"
    folder: "/static/content/projekte"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "title", widget: "text" }
      - { label: "Headline für Unterseite", name: "header", widget: "text" }
      - { label: "Grafik und ...", name: "grafikund", widget: "string" }
      - { label: "Reihenfolge/Priorität (höher wird in Übersicht früher angezeigt)", name: "order", widget: "string", default: "0" }
      - { label: "Kategorie", name: "category", widget: "select", multiple: false, options: ["Raum", "Grafik", "Marke", "Online", "Spiel"], default: ["Grafik"] }
      - { label: "KundInnen", name: "client", widget: "string", required: false }
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: false
      - { label: 'Farbe des Textes bei Hover auf Thumbnail', name: 'thumbhovercolour', widget: 'color', allowInput: true, default: '#f5f4f0' }
      - {label: "Großes Thumbnail", name: "bigthumbnail", widget: "boolean", default: false}

      - { label: "Info-Text: Wer? Was? Wieso?", name: "werwaswieso", widget: "text", required: false }
      - { label: "Info-Text: Das hat Erika gemacht", name: "erikamacht", widget: "text", required: false }

      - label: 'Inhalte'
        name: 'content'
        widget: 'list'
        types:
          - label: 'Bildschirmbreites Bild'
            name: 'coverimageobject'
            widget: object
            summary: '{{fields.coverimage}}'
            fields:
              - label: "Full-Sized Bild"
                name: "coverimage"
                widget: "image"
                choose_url: true
                media_library:
                  config:
                    multiple: false
              - { label: Alt-Text / Beschreibung, name: alttext, widget: string, default: 'Bild' }
          - label: 'Zwei Bilder nebeneinander'
            name: 'doubleimageobject'
            widget: object
            summary: '{{fields.doubleimage}}'
            fields:
              - label: "erstes Bild"
                name: "doubleimage1"
                widget: "image"
                choose_url: true
                media_library:
                  config:
                    multiple: false
              - { label: Alt-Text / Beschreibung für Bild 1, name: alttext1, widget: string, default: 'Bild' }
              - label: "zweites Bild"
                name: "doubleimage2"
                widget: "image"
                choose_url: true
                media_library:
                  config:
                    multiple: false
              - { label: Alt-Text / Beschreibung für Bild 2, name: alttext2, widget: string, default: 'Bild' }
          - label: 'Hochkant Bild'
            name: 'portraitimageobject'
            widget: object
            summary: '{{fields.portraitimage}}'
            fields:
              - label: "Hochkant Bild"
                name: "portraitimage"
                widget: "image"
                choose_url: true
                media_library:
                  config:
                    multiple: false
              - { label: Alt-Text / Beschreibung, name: alttext, widget: string, default: 'Bild' }
          - label: 'Youtube Link'
            name: 'youtubelink'
            widget: object
            fields:
              - { label: URL, name: url, widget: string, default: 'https://www.youtube-nocookie.com/embed/HJ4boSbOX7I' }
          - label: 'eigenes mp4 Video'
            name: 'mp4fileobject'
            widget: object
            fields:
            - label: "Video Datei (vorher komprimieren! mehr als 2MB ist schlecht)"
              name: "mp4file"
              widget: "file"
              media_library:
                config:
                  multiple: false
                media_folder:
                  /static/cmsfiles
